const videos = [];
videos[0] = `video of African Wild Dog, environment detail focus, in Scrubland, sunset red glow, low angle, BBC Earth style, 5 seconds`;
videos[1] = `video of African Wild Dog, becomes alert, in Scrubland, harsh daylight, handheld, hyper realistic, 5 seconds`;
videos[2] = `video of African Wild Dog, rapid escape, in Scrubland, storm clouds, tracking shot, 8K detail, 5 seconds`;
videos[3] = `video of African Wild Dog, running at speed, in Scrubland, storm clouds, aerial drone, hyper realistic, 5 seconds`;
videos[4] = `video of African Wild Dog, life-or-death struggle, in Scrubland, sunset red glow, close-up, 8K detail, 5 seconds`;
videos[5] = `video of African Wild Dog, intense confrontation, in Scrubland, storm clouds, handheld, cinematic depth, 5 seconds`;
videos[6] = `video of African Wild Dog, slow breathing, in Scrubland, sunset red glow, handheld, hyper realistic, 5 seconds`;
module.exports = videos;